import json
from typing import Dict, Any

def generate_pdf(resume_data: Dict[str, Any], template_id: str) -> bytes:
    try:
        from fpdf import FPDF
    except ImportError:
        raise Exception("Missing fpdf library. Run 'pip install fpdf2'")
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Very basic PDF generation logic for the massive template engine
    # In a full implementation, this uses coordinate mapping per template_id
    pdf.set_font("Arial", 'B', 16)
    name = resume_data.get("personal_info", {}).get("name", "John Doe")
    pdf.cell(200, 10, text=name, new_x="LMARGIN", new_y="NEXT", align='C')
    
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, text="Generated by AI Resume Studio - " + template_id, new_x="LMARGIN", new_y="NEXT", align='C')
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, text="Skills", new_x="LMARGIN", new_y="NEXT", align='L')
    pdf.set_font("Arial", size=10)
    skills = ", ".join(resume_data.get("skills", ["Python", "React", "AI"]))
    pdf.multi_cell(0, 10, text=skills)

    return pdf.output(dest='S').encode('latin-1')

def generate_docx(resume_data: Dict[str, Any], template_id: str):
    try:
        from docx import Document
    except ImportError:
        raise Exception("Missing python-docx library. Run 'pip install python-docx'")
    
    import io
    doc = Document()
    name = resume_data.get("personal_info", {}).get("name", "John Doe")
    doc.add_heading(name, 0)
    doc.add_paragraph(f"Generated by AI Resume Studio - {template_id}")
    
    doc.add_heading('Skills', level=1)
    skills = ", ".join(resume_data.get("skills", ["Python", "React", "AI"]))
    doc.add_paragraph(skills)
    
    f = io.BytesIO()
    doc.save(f)
    f.seek(0)
    return f.read()
