services:
  - type: web
    name: ai-resume-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://ai-resume-parser-upwf.onrender.com
